### generated by argx/utils::convert-alias-file

# export alias a = ai-assistant #[entry]
export def a [...message: string, --provider(-p): string, --model(-m): string, --system: string, --response-indicator: string, --image(-i): string, --audio(-a): string, --out(-o), --quiet(-q), --ensure-prompt, --think, --debug, --refresh] {
    let n = $in
    use llm *
    $n | ai-assistant  ...$message --provider $provider --model $model --system $system --response-indicator $response_indicator --image $image --audio $audio --out=$out --quiet=$quiet --ensure-prompt=$ensure_prompt --think=$think --debug=$debug --refresh=$refresh
}
# export alias asn = ai-session #[entry]
export def asn [--all(-a)] {
    let n = $in
    use llm *
    $n | ai-session --all=$all
}